cache:
    paths:
        - .

build:
    stage: build
    image: maven:3.3.9
    script:
        - mvn -f webgoat/pom.xml package

.lifecycle-evaluation: &lifecycle-evaluation
    stage: test
    image: registry.gitlab.com/hokiegeek/nexus-lifecycle-gitlab:1.65.0
    script:
        - evaluate
    after_script:
       - gitlab

evaluate-build:
    <<: *lifecycle-evaluation
    variables:
        IQ_STAGE: build
    except:
        - /^stable-.*$/
        - tags
        - master

evaluate-staging:
    <<: *lifecycle-evaluation
    variables:
        IQ_STAGE: stage-release
    only:
        - master

evaluate-release:
    <<: *lifecycle-evaluation
    variables:
        IQ_STAGE: release
    only:
        - tags
