trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: nexus-lifecycle
- name: iq_cli_jar
  value: nexus-iq-cli-1.64.0-02.jar

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'webgoat/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    goals: 'package'

- task: DownloadSecureFile@1
  inputs:
    secureFile: 'https://download.sonatype.com/clm/scanner/'$(iq_cli_jar)

- script: |
    java -jar $(Agent.TempDirectory)/$(iq_cli_jar) \
      -s $(NEXUS_IQ_URL) \
      -a $(NEXUS_IQ_USERNAME):$(NEXUS_IQ_PASSWORD) \
      -i WebGoatAzure \
      -t build \
      webgoat/target
  displayName: 'Nexus Lifecycle evaluation'
