trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'webgoat/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    goals: 'package'

- task: JavaToolInstaller@0
    inputs:
      versionSpec: '8'
      jdkArchitectureOption: x64

- script: |
    curl -o /tmp/nexus-iq-cli.jar https://download.sonatype.com/clm/scanner/nexus-iq-cli-1.64.0-02.jar
    java -version
    # java -jar /tmp/nexus-iq-cli.jar \
    #   -s ${NEXUS_IQ_URL} \
    #   -a ${NEXUS_IQ_USERNAME}:${NEXUS_IQ_PASSWORD} \
    #   -i WebGoatBitBucket \
    #   -t ${NEXUS_IQ_STAGE} \
    #   webgoat/target
  displayName: 'Run Nexus Lifecycle evaluation'
