image: maven:3.3.9

lifecycle-evaluation: &lifecycle-evaluation
  name: Evaluate with Nexus Lifecycle
  image: sonatype/nexus-iq-cli:1.1
  script:
      - /sonatype/evaluate -s ${NEXUS_IQ_URL} -a ${NEXUS_IQ_USERNAME}:${NEXUS_IQ_PASSWORD} -i WebGoatBitBucket -t ${NEXUS_IQ_STAGE} webgoat/target

pipelines:
  default:
    - step:
        name: Build the code
        caches:
          - maven
        artifacts:
          - webgoat/target/*.war
        script:
          - mvn -f webgoat/pom.xml package
    - step:
        <<: *lifecycle-evaluation
        deployment: test
  branches:
    master:
      - step:
          <<: *lifecycle-evaluation
          deployment: staging
    feature/*:
      - step:
          <<: *lifecycle-evaluation
          deployment: staging
  pull-requests:
    '**':
      - step:
          <<: *lifecycle-evaluation
          deployment: staging
  tags:
    release-*:
      - step:
          <<: *lifecycle-evaluation
          deployment: production
