image: maven:3.3.9

pipelines:
  default:
    - step:
        name: Build the code
        caches:
          - maven
        script:
          - mvn -f webgoat/pom.xml package
    - step:
        name: Evaluate with Nexus
        image: sonatype/nexus-iq-cli:1.1
        caches:
          - maven
        artifacts:
          - WebGoatBitBucket-policy-eval-report.html
        script:
          - /sonatype/evaluate -i WebGoatBitBucket -t build target
