image: maven:3.3.9

pipelines:
  default:
    - step:
        name: Build the code
        caches:
          - maven
        artifacts:
          - webgoat/target/*.war
        script:
          - mvn -f webgoat/pom.xml package
    - step:
        name: Evaluate with Nexus Lifecycle
        image: sonatype/nexus-iq-cli:1.1
        script:
            - /sonatype/evaluate -s ${NEXUS_IQ_URL} -a ${NEXUS_IQ_USERNAME}:${NEXUS_IQ_PASSWORD} -i WebGoatBitBucket -t build webgoat/target
