image: maven:3.3.9

pipelines:
  default:
    - step:
        name: Build the code
        caches:
          - target
        script:
          - mvn -f webgoat/pom.xml package
    - step:
        name: Evaluate with Nexus
        image: sonatype/nexus-iq-cli:1.1
        caches:
          - target
        artifacts:
          - WebGoatBitBucket-policy-eval-report.html
        script:
            - /sonatype/evaluate -s ${NEXUS_IQ_URL} -a ${NEXUS_IQ_USERNAME}:${NEXUS_IQ_PASSWORD} -i WebGoatBitBucket -t build target
